In [ ]:
#Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [ ]:
import numpy as np

In [ ]:
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [ ]:
#Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [14]:
import numpy as np
list1=[]
list2=[]
for i in range(5):
    number1 = int(input())
    number2 = int(input())
    list1.append(number1)
    list2.append(number2)
    array1=np.array(list1)
    array2= np.array(list2)
    array3=array1+array2

print(array3)
print(np.sort(array3))

23
1
45
2
67
3
89
56
78
56
[ 24  47  70 145 134]
[ 24  47  70 134 145]


In [ ]:
#Question 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [ ]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)


No. of dimensions:  2
Size of array:  6


In [ ]:
#Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [ ]:
import numpy as np 
  
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b))) 

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Questions 6:
How to get unique items and counts of unique items


In [15]:
import numpy as np
arr=np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)

uniqueValues, occurCount = np.unique(arr, return_counts=True)
print("Unique Values : " , uniqueValues)
print("Occurrence Count : ", occurCount)

Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
Occurrence Count :  [3 2 2 2 1 1 1 1]
